name: Serveo RDP Tunnel

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set Password for runneradmin
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Start Serveo Tunnel
      shell: pwsh
      run: |
        # Start the Serveo SSH tunnel in the background.
        Start-Process -NoNewWindow -FilePath "ssh" -ArgumentList '-o StrictHostKeyChecking=no -R 3389:localhost:3389 serveo.net -N'
        Write-Output "Tunnel initiated. Check the workflow logs for a line like 'Forwarding TCP connections from serveo.net:<port>'."
