name: Serveo RDP Tunnel

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set Password for runneradmin
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Start Serveo Tunnel with random port
      shell: pwsh
      run: |
        # Start the Serveo SSH tunnel in the background, letting Serveo choose an available remote port.
        Start-Process -NoNewWindow -FilePath "ssh" -ArgumentList '-o', 'StrictHostKeyChecking=no', '-R', '0:localhost:3389', 'serveo.net', '-N' -RedirectStandardOutput serveo_out.log -RedirectStandardError serveo_err.log

        # Wait up to 30 seconds for the tunnel to initialize and log the public address.
        $tunnelAddress = ""
        $timeout = 30
        while ($timeout -gt 0 -and -not $tunnelAddress) {
          Start-Sleep -Seconds 2
          # Look for the forwarding line in both log files.
          $tunnelAddress = (Get-Content serveo_err.log, serveo_out.log | Select-String -Pattern 'Forwarding TCP connections from').Line
          $timeout -= 2
        }

        if ($tunnelAddress) {
          Write-Output "Tunnel Address Found: $tunnelAddress"
          # Extract the actual host and port from the line (assuming the line contains something like:
          # "Forwarding TCP connections from serveo.net:XXXXX")
          if ($tunnelAddress -match 'serveo\.net:(\d+)') {
            $port = $Matches[1]
            Write-Output "You can connect using: serveo.net:$port"
          } else {
            Write-Output "Could not parse the tunnel address. Full line: $tunnelAddress"
          }
        } else {
          Write-Output "Tunnel address not found in logs."
          Write-Output "StdOut Log:"
          Get-Content serveo_out.log
          Write-Output "StdErr Log:"
          Get-Content serveo_err.log
        }
