name: Windows RDP
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Chrome Remote Desktop
      run: |
        sudo apt update
        sudo apt install -y wget curl
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo dpkg -i chrome-remote-desktop_current_amd64.deb
        sudo apt --fix-broken install -y
        sudo systemctl enable chrome-remote-desktop
        echo "DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0ASVgi3IOAHTRfOx7aOWXiYOD2pEejrem3bemmwpYM97qeUailQinR1-8BLTcZEqYfUqCZA" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)" | bash
    - name: Keep Alive
      run: sleep 86400
